
# the channel to show logs
LOGS_CHANNEL: "1084476544967249940"

# the role to check has icon or no
SPECIAL_ROLE: "1141759520889114634"

#character setting

SPIRIT_PER_LEVEL: 10
MAX_EXP: 35
MIN_EXP: 10
X: 0.05
Y: 2

MAX_COINS: 1000
MIN_COINS: 250

STAT_PROBABILITY: 0.05

SMALL_STAT_INCREASE: 0.01
BIG_STAT_INCREASE: 0.5