
# the channel to show logs
LOGS_CHANNEL: "1084476544967249940"

# the role to check has icon or no
SPECIAL_ROLE: "1141759520889114634"

#limit
EXP_PER_DAY: 3000
WORK_PER_WEEK: 7000
MAX_LEVEL: 10

#character setting

STAT_PER_LEVEL: 10
MAX_EXP: 50
MIN_EXP: 10
X: 0.05
Y: 2

MAX_COINS: 5000
MIN_COINS: 1000