
# THE SPECIAL ROLE ID TO ADD ICONS TO THE USERNAME
SPECIAL_ROLE: "1141759520889114634"


# EXP SETTINGS
SPIRIT_PER_LEVEL: 10
MAX_EXP: 35
MIN_EXP: 10
X: 0.05
Y: 2

# COINS SETTINGS
MAX_COINS: 1000
MIN_COINS: 250

# STATS SETTINGS
STAT_PROBABILITY: 0.05

SMALL_STAT_INCREASE: 0.01
BIG_STAT_INCREASE: 0.05

#OBJECTS EMOJI
CASH_EMOJI: ":moneybag:"

# NOTIFICATIONS EMOJI
NOTICE_EMOJI: "📍"
ERROR_EMOJI: "❎"
SUCCESS_EMOJI: "✅"
WARNING_EMOJI: "⚠️"

#STATS EMOJI
HP_EMOJI: "<:HP:1179297178267693096>"
MP_EMOJI: "<:MP:1180026576272896051>"
AGI_EMOJI: "\\:AGI:"
STR_EMOJI: "<:STR:1179304508636008458>"
CR_EMOJI: "<:CR:1179305232862289960>"
PR_EMOJI: "<:PR:1179305691266162688>"

#SKILLS EMOJI
# ATTACK_EMOJI: "⚔"
# SPEED_EMOJI: "🏃"

#COGS NAME
GAME: "Game"
MODERATOR: "Moderator"

#COLORS
BLACK: 0x000000
WHITE: 0xFFFFFF
RED: 0xFF0000
GREEN: 0x00FF00
BLUE: 0x0000FF

